KiemTra/ViewComponents/TranDauMenuViewComponent.cs
using KiemTra.Repository;
using Microsoft.AspNetCore.Mvc;

namespace KiemTra.ViewComponents
{
    public class TranDauMenuViewComponent: ViewComponent
    {
        private readonly ITranDauRepository _tranDauRepository;
        public TranDauMenuViewComponent(ITranDauRepository tranDauRepository)
        {
            _tranDauRepository = tranDauRepository;
        }
        public IViewComponentResult Invoke()
        {
            var trandau = _tranDauRepository.GetAll().OrderBy(x => x.TranDauId);
            return View(trandau);
        }
    }
}

KiemTra/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - KiemTra</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/KiemTra.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">KiemTra</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - KiemTra - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

KiemTra/Views/Shared/_LayoutElectronix.cshtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title>Electronix Store</title>
    <meta http-equiv="Content-Type" content="text/html; charset=windows-1252" />
    <link rel="stylesheet" type="text/css" href="../LayoutElectric/style.css" />
    <!--[if IE 6]>
    <link rel="stylesheet" type="text/css" href="iecss.css" />
    <![endif]-->
    <script type="text/javascript" src="../LayoutElectric/js/boxOver.js"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
</head>
<body>
    <div id="main_container">
        <div class="top_bar">
            <div class="top_search">
                <div class="search_text"><a href="#">Advanced Search</a></div>
                <input type="text" class="search_input" name="search" />
                <input type="image" src="../LayoutElectric/images/search.gif" class="search_bt" />
            </div>
            <div class="languages">
                <div class="lang_text">Languages:</div>
                <a href="#" class="lang"><img src="../LayoutElectric/images/en.gif" alt="" border="0" /></a> <a href="#" class="lang"><img src="../LayoutElectric/images/de.gif" alt="" border="0" /></a>
            </div>
        </div>
        <div id="header">
            <div id="logo"> <a href="#"><img src="../LayoutElectric/images/logo.png" alt="" border="0" width="237" height="140" /></a> </div>
            <div class="oferte_content">
                <div class="top_divider"><img src="../LayoutElectric/images/header_divider.png" alt="" width="1" height="164" /></div>
                <div class="oferta">
                    <div class="oferta_content">
                        <img src="../LayoutElectric/images/laptop.png" width="94" height="92" alt="" border="0" class="oferta_img" />
                        <div class="oferta_details">
                            <div class="oferta_title">Samsung GX 2004 LM</div>
                            <div class="oferta_text"> Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco </div>
                            <a href="details.html" class="details">details</a>
                        </div>
                    </div>
                    <div class="oferta_pagination"> <span class="current">1</span> <a href="#">2</a> <a href="#">3</a> <a href="#">4</a> <a href="#">5</a> </div>
                </div>
                <div class="top_divider"><img src="../LayoutElectric/images/header_divider.png" alt="" width="1" height="164" /></div>
            </div>
            <!-- end of oferte_content-->
        </div>
        <div id="main_content">
            <div id="menu_tab">
                <div class="left_menu_corner"></div>
                <ul class="menu">
                    <li><a href="#" class="nav1"> Home</a></li>
                    <li class="divider"></li>
                    <li><a href="#" class="nav2">Products</a></li>
                    <li class="divider"></li>
                    <li><a href="#" class="nav3">Specials</a></li>
                    <li class="divider"></li>
                    <li><a href="#" class="nav4">My account</a></li>
                    <li class="divider"></li>
                    <li><a href="#" class="nav4">Sign Up</a></li>
                    <li class="divider"></li>
                    <li><a href="#" class="nav5">Shipping</a></li>
                    <li class="divider"></li>
                    <li><a href="contact.html" class="nav6">Contact Us</a></li>
                    <li class="divider"></li>
                    <li class="currencies">
                        Currencies
                        <select>
                            <option>US Dollar</option>
                            <option>Euro</option>
                        </select>
                    </li>
                </ul>
                <div class="right_menu_corner"></div>
            </div>
            <!-- end of menu tab -->
            <div class="crumb_navigation"> Navigation: <span class="current">Home</span> </div>
            <div class="left_content">
                <div class="title_box">Đề số 08</div>               
                    @await Component.InvokeAsync("TranDauMenu")  
                <div class="title_box">Special Products</div>
                <div class="border_box">
                    <div class="product_title"><a href="details.html">Motorola 156 MX-VL</a></div>
                    <div class="product_img"><a href="details.html"><img src="../LayoutElectric/images/laptop.png" alt="" border="0" /></a></div>
                    <div class="prod_price"><span class="reduce">350$</span> <span class="price">270$</span></div>
                </div>
                <div class="title_box">Newsletter</div>
                <div class="border_box">
                    <input type="text" name="newsletter" class="newsletter_input" value="your email" />
                    <a href="#" class="join">join</a>
                </div>
                <div class="banner_adds"> <a href="#"><img src="../LayoutElectric/images/bann2.jpg" alt="" border="0" /></a> </div>
            </div>
            <!-- end of left content -->
            <div class="center_content" id="displayTrongTai">
                @RenderBody()
            </div>
            <!-- end of center content -->
            <div class="right_content">
                <div class="shopping_cart">
                    <div class="cart_title">Shopping cart</div>
                    <div class="cart_details">
                        3 items <br />
                        <span class="border_cart"></span> Total: <span class="price">350$</span>
                    </div>
                    <div class="cart_icon"><a href="#" title="header=[Checkout] body=[&nbsp;] fade=[on]"><img src="../LayoutElectric/images/shoppingcart.png" alt="" width="48" height="48" border="0" /></a></div>
                </div>
                <div class="title_box">What’s new</div>
                <div class="border_box">
                    <div class="product_title"><a href="details.html">Motorola 156 MX-VL</a></div>
                    <div class="product_img"><a href="details.html"><img src="../LayoutElectric/images/p2.gif" alt="" border="0" /></a></div>
                    <div class="prod_price"><span class="reduce">350$</span> <span class="price">270$</span></div>
                </div>
                <div class="title_box">Manufacturers</div>
                <ul class="left_menu">
                    <li class="odd"><a href="#">Sony</a></li>
                    <li class="even"><a href="#">Samsung</a></li>
                    <li class="odd"><a href="#">Daewoo</a></li>
                    <li class="even"><a href="#">LG</a></li>
                    <li class="odd"><a href="#">Fujitsu Siemens</a></li>
                    <li class="even"><a href="#">Motorola</a></li>
                    <li class="odd"><a href="#">Phillips</a></li>
                    <li class="even"><a href="#">Beko</a></li>
                </ul>
                <div class="banner_adds"> <a href="#"><img src="../LayoutElectric/images/bann1.jpg" alt="" border="0" /></a> </div>
            </div>
            <!-- end of right content -->
        </div>
        <!-- end of main content -->
        <div class="footer">
            <div class="left_footer"> <img src="../LayoutElectric/images/footer_logo.png" alt="" width="170" height="49" /> </div>
            <div class="center_footer">
                Template name. All Rights Reserved 2008<br />
                <a href="http://csscreme.com"><img src="../LayoutElectric/images/csscreme.jpg" alt="csscreme" border="0" /></a><br />
                <img src="../LayoutElectric/images/payment.gif" alt="" />
            </div>
            <div class="right_footer"> <a href="#">home</a> <a href="#">about</a> <a href="#">sitemap</a> <a href="#">rss</a> <a href="contact.html">contact us</a> </div>
        </div>
    </div>
    <!-- end of main_container -->
</body>
</html>

KiemTra/Views/Shared/_LayoutShopper.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<title>Bootstrap E-commerce Templates</title>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta name="description" content="">
	<!--[if ie]><meta content='IE=8' http-equiv='X-UA-Compatible'/><![endif]-->
	<!-- bootstrap -->
	<link href="../Shopper/bootstrap/css/bootstrap.min.css" rel="stylesheet">
	<link href="../Shopper/bootstrap/css/bootstrap-responsive.min.css" rel="stylesheet">

	<link href="../Shopper/themes/css/bootstrappage.css" rel="stylesheet" />

	<!-- global styles -->
	<link href="../Shopper/themes/css/flexslider.css" rel="stylesheet" />
	<link href="../Shopper/themes/css/main.css" rel="stylesheet" />

	<!-- scripts -->
	<script src="../Shopper/themes/js/jquery-1.7.2.min.js"></script>
	<script src="../Shopper/bootstrap/js/bootstrap.min.js"></script>
	<script src="../Shopper/themes/js/superfish.js"></script>
	<script src="../Shopper/themes/js/jquery.scrolltotop.js"></script>
	<!--[if lt IE 9]>
		<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
		<script src="js/respond.min.js"></script>
	<![endif]-->
</head>
<body>
	<div id="top-bar" class="container">
		<div class="row">
			<div class="span4">
				<form method="POST" class="search_form">
					<input type="text" class="input-block-level search-query" Placeholder="eg. T-sirt">
				</form>
			</div>
			<div class="span8">
				<div class="account pull-right">
					<ul class="user-menu">
						<li><a href="#">My Account</a></li>
						<li><a href="cart.html">Your Cart</a></li>
						<li><a href="checkout.html">Checkout</a></li>
						<li><a href="register.html">Login</a></li>
					</ul>
				</div>
			</div>
		</div>
	</div>
	<div id="wrapper" class="container">
		<section class="navbar main-menu">
			<div class="navbar-inner main-menu">
				<a href="index.html" class="logo pull-left"><img src="../Shopper/themes/images/logo.png" class="site_logo" alt=""></a>
				<nav id="menu" class="pull-right">
					<ul>
						<li>
							<a>Trận đấu ID</a>
							<ul>
								@await Component.InvokeAsync("TranDauMenu")
							</ul>
						</li>
						<li><a href="./products.html">Man</a></li>
						<li>
							<a href="./products.html">Sport</a>
							<ul>
								<li><a href="./products.html">Gifts and Tech</a></li>
								<li><a href="./products.html">Ties and Hats</a></li>
								<li><a href="./products.html">Cold Weather</a></li>
							</ul>
						</li>
						<li><a href="./products.html">Hangbag</a></li>
						<li><a href="./products.html">Best Seller</a></li>
						<li><a href="./products.html">Top Seller</a></li>
					</ul>
				</nav>
			</div>
		</section>
		<section class="homepage-slider" id="home-slider">
			<div class="flexslider">
				<ul class="slides">
					<li>
						<img src="../Shopper/themes/images/carousel/banner-1.jpg" alt="" />
					</li>
					<li>
						<img src="../Shopper/themes/images/carousel/banner-2.jpg" alt="" />
						<div class="intro">
							<h1>Mid season sale</h1>
							<p><span>Up to 50% Off</span></p>
							<p><span>On selected items online and in stores</span></p>
						</div>
					</li>
				</ul>
			</div>
		</section>
		<section class="header_text">
			We stand for top quality templates. Our genuine developers always optimized bootstrap commercial templates.
			<br />Don't miss to use our cheap abd best bootstrap templates.
		</section>
		<section class="main-content">
			<div class="row">
				<div class="span12">
					<div class="row">
						<div class="span12">
							<h4 class="title">
								<span class="pull-left"><span class="text"><span class="line">Feature <strong>Products</strong></span></span></span>
								<span class="pull-right">
									<a class="left button" href="#myCarousel" data-slide="prev"></a><a class="right button" href="#myCarousel" data-slide="next"></a>
								</span>
							</h4>
							<div id="myCarousel" class="myCarousel carousel slide">
								<div class="carousel-inner">
									<div class="active item">
										<ul class="thumbnails" id="displayCauThu">
											<h4>@TempData["Message"]</h4>
											@RenderBody()
										</ul>
									</div>								
								</div>
							</div>
						</div>
					</div>
					<br />
					<div class="row">
						<div class="span12">
							<h4 class="title">
								<span class="pull-left"><span class="text"><span class="line">Latest <strong>Products</strong></span></span></span>
								<span class="pull-right">
									<a class="left button" href="#myCarousel-2" data-slide="prev"></a><a class="right button" href="#myCarousel-2" data-slide="next"></a>
								</span>
							</h4>
							<div id="myCarousel-2" class="myCarousel carousel slide">
								<div class="carousel-inner">
									<div class="active item">
										<ul class="thumbnails">
											<li class="span3">
												<div class="product-box">
													<span class="sale_tag"></span>
													<p><a href="product_detail.html"><img src="../Shopper/themes/images/cloth/bootstrap-women-ware2.jpg" alt="" /></a></p>
													<a href="product_detail.html" class="title">Ut wisi enim ad</a><br />
													<a href="products.html" class="category">Commodo consequat</a>
													<p class="price">$25.50</p>
												</div>
											</li>
											<li class="span3">
												<div class="product-box">
													<p><a href="product_detail.html"><img src="../Shopper/themes/images/cloth/bootstrap-women-ware1.jpg" alt="" /></a></p>
													<a href="product_detail.html" class="title">Quis nostrud exerci tation</a><br />
													<a href="products.html" class="category">Quis nostrud</a>
													<p class="price">$17.55</p>
												</div>
											</li>
											<li class="span3">
												<div class="product-box">
													<p><a href="product_detail.html"><img src="../Shopper/themes/images/cloth/bootstrap-women-ware6.jpg" alt="" /></a></p>
													<a href="product_detail.html" class="title">Know exactly turned</a><br />
													<a href="products.html" class="category">Quis nostrud</a>
													<p class="price">$25.30</p>
												</div>
											</li>
											<li class="span3">
												<div class="product-box">
													<p><a href="product_detail.html"><img src="../Shopper/themes/images/cloth/bootstrap-women-ware5.jpg" alt="" /></a></p>
													<a href="product_detail.html" class="title">You think fast</a><br />
													<a href="products.html" class="category">World once</a>
													<p class="price">$25.60</p>
												</div>
											</li>
										</ul>
									</div>
									<div class="item">
										<ul class="thumbnails">
											<li class="span3">
												<div class="product-box">
													<p><a href="product_detail.html"><img src="../Shopper/themes/images/cloth/bootstrap-women-ware4.jpg" alt="" /></a></p>
													<a href="product_detail.html" class="title">Know exactly</a><br />
													<a href="products.html" class="category">Quis nostrud</a>
													<p class="price">$45.50</p>
												</div>
											</li>
											<li class="span3">
												<div class="product-box">
													<p><a href="product_detail.html"><img src="../Shopper/themes/images/cloth/bootstrap-women-ware3.jpg" alt="" /></a></p>
													<a href="product_detail.html" class="title">Ut wisi enim ad</a><br />
													<a href="products.html" class="category">Commodo consequat</a>
													<p class="price">$33.50</p>
												</div>
											</li>
											<li class="span3">
												<div class="product-box">
													<p><a href="product_detail.html"><img src="../Shopper/themes/images/cloth/bootstrap-women-ware2.jpg" alt="" /></a></p>
													<a href="product_detail.html" class="title">You think water</a><br />
													<a href="products.html" class="category">World once</a>
													<p class="price">$45.30</p>
												</div>
											</li>
											<li class="span3">
												<div class="product-box">
													<p><a href="product_detail.html"><img src="../Shopper/themes/images/cloth/bootstrap-women-ware1.jpg" alt="" /></a></p>
													<a href="product_detail.html" class="title">Quis nostrud exerci</a><br />
													<a href="products.html" class="category">Quis nostrud</a>
													<p class="price">$25.20</p>
												</div>
											</li>
										</ul>
									</div>
								</div>
							</div>
						</div>
					</div>
					<div class="row feature_box">
						<div class="span4">
							<div class="service">
								<div class="responsive">
									<img src="../Shopper/themes/images/feature_img_2.png" alt="" />
									<h4>MODERN <strong>DESIGN</strong></h4>
									<p>Lorem Ipsum is simply dummy text of the printing and printing industry unknown printer.</p>
								</div>
							</div>
						</div>
						<div class="span4">
							<div class="service">
								<div class="customize">
									<img src="../Shopper/themes/images/feature_img_1.png" alt="" />
									<h4>FREE <strong>SHIPPING</strong></h4>
									<p>Lorem Ipsum is simply dummy text of the printing and printing industry unknown printer.</p>
								</div>
							</div>
						</div>
						<div class="span4">
							<div class="service">
								<div class="support">
									<img src="../Shopper/themes/images/feature_img_3.png" alt="" />
									<h4>24/7 LIVE <strong>SUPPORT</strong></h4>
									<p>Lorem Ipsum is simply dummy text of the printing and printing industry unknown printer.</p>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</section>
		<section class="our_client">
			<h4 class="title"><span class="text">Manufactures</span></h4>
			<div class="row">
				<div class="span2">
					<a href="#"><img alt="" src="../Shopper/themes/images/clients/14.png"></a>
				</div>
				<div class="span2">
					<a href="#"><img alt="" src="../Shopper/themes/images/clients/35.png"></a>
				</div>
				<div class="span2">
					<a href="#"><img alt="" src="../Shopper/themes/images/clients/1.png"></a>
				</div>
				<div class="span2">
					<a href="#"><img alt="" src="../Shopper/themes/images/clients/2.png"></a>
				</div>
				<div class="span2">
					<a href="#"><img alt="" src="../Shopper/themes/images/clients/3.png"></a>
				</div>
				<div class="span2">
					<a href="#"><img alt="" src="../Shopper/themes/images/clients/4.png"></a>
				</div>
			</div>
		</section>
		<section id="footer-bar">
			<div class="row">
				<div class="span3">
					<h4>Navigation</h4>
					<ul class="nav">
						<li><a href="./index.html">Homepage</a></li>
						<li><a href="./about.html">About Us</a></li>
						<li><a href="./contact.html">Contac Us</a></li>
						<li><a href="./cart.html">Your Cart</a></li>
						<li><a href="./register.html">Login</a></li>
					</ul>
				</div>
				<div class="span4">
					<h4>My Account</h4>
					<ul class="nav">
						<li><a href="#">My Account</a></li>
						<li><a href="#">Order History</a></li>
						<li><a href="#">Wish List</a></li>
						<li><a href="#">Newsletter</a></li>
					</ul>
				</div>
				<div class="span5">
					<p class="logo"><img src="../Shopper/themes/images/logo.png" class="site_logo" alt=""></p>
					<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. the  Lorem Ipsum has been the industry's standard dummy text ever since the you.</p>
					<br />
					<span class="social_icons">
						<a class="facebook" href="#">Facebook</a>
						<a class="twitter" href="#">Twitter</a>
						<a class="skype" href="#">Skype</a>
						<a class="vimeo" href="#">Vimeo</a>
					</span>
				</div>
			</div>
		</section>
		<section id="copyright">
			<span>Copyright 2013 bootstrappage template  All right reserved.</span>
		</section>
	</div>
	<script src="../Shopper/themes/js/common.js"></script>
	<script src="../Shopper/themes/js/jquery.flexslider-min.js"></script>
	<script type="text/javascript">
		$(function () {
			$(document).ready(function () {
				$('.flexslider').flexslider({
					animation: "fade",
					slideshowSpeed: 4000,
					animationSpeed: 600,
					controlNav: false,
					directionNav: true,
					controlsContainer: ".flex-container" // the container that holds the flexslider
				});
			});
		});
	</script>
</body>
</html>